### PR TITLE
added 2 publications

### PR DESCRIPTION
**Pull request by GraceGSy**

### CODE REVIEW

**Comment by arpitnarechania** [comment]
@GraceGSy , please re-check "2021-vaine-visualization-and-ai-for-natural-experiments.md"; the publication "title", "venue" are incorrect.

**Review by arpitnarechania — CHANGES_REQUESTED** [review]
Please re-check "2021-vaine-visualization-and-ai-for-natural-experiments.md"; the publication "title", "venue" seem incorrect.

**Comment by GraceGSy** [comment]
updated VAINE

**Review by arpitnarechania — APPROVED** [review]
Looks good!

**Pull request merged**
