### PR TITLE
Adding Alex Y. and home page link for CardiacAR

### PR DESCRIPTION
**Pull request by AlexanderHYang**

### CODE REVIEW

**Review by xiaohk — CHANGES_REQUESTED** [review]
Thanks @AlexanderHYang, can you reduce the size of `alexyang.png` a bit? Right now it is 8MB. You can use this one attached (I resized it, 296KB).

alexyang

**Comment by AlexanderHYang** [comment]
Just updated the picture to a smaller size.

**Review by xiaohk — APPROVED** [review]

**Comment by xiaohk** [comment]
Thanks! Merged.

**Comment by arpitnarechania** [comment]
Deployed.

**Pull request merged**
